Pytest of grodecoder.py on all the file in data/exemples/
pierrepo/grodecoder pull request #55
Opened 2024-06-26 18:24 UTC by KarinDuong

Pytest of grodecoder.py on all the file in data/exemples/, by comparing the JSON output (for the key 'inventory') that we get with a reference output (in tests/data/)

2024-06-28 09:54 UTC, pierrepo commented
@KarinDuong could you remove `step7_1.gro` and `step_1.json`?

2024-06-28 10:10 UTC, KarinDuong commented on tests/test_grodecoder.py
> +    assert JSON_content_test["inventory"] == JSON_content_data["inventory"]
Done ! :white_check_mark:

2024-06-28 10:24 UTC, pierrepo commented
> @KarinDuong could you remove `step7_1.gro` and `step_1.json`?

Also `step7_1.gro`

2024-06-28 11:36 UTC, pierrepo commented
@KarinDuong `test_grodecoder.py` should stay in the `tests` directory

2024-07-01 14:01 UTC, pierrepo requested changes

2024-07-01 15:30 UTC, pierrepo commented
@KarinDuong could you please blackify your code?

2024-07-02 09:24 UTC, pierrepo approved these changes

2024-07-02 09:25 UTC, pierrepo commented
@KarinDuong code looks good. Could we merge?

2024-07-02 11:32 UTC, merged